language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
  # Prevent "Please tell me who you are" errors for certain DZIL configs
  - git config --global user.name "TravisCI"

  # install optional DBD::SQLite, so more tests can run
  - cpanm --quiet --notest --skip-satisfied DBD::SQLite
