---
abstract: 'Perl implementation of DMARC'
author:
  - 'Matt Simerson <msimerson@cpan.org>'
  - 'Davide Migliavacca <shari@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-DMARC
requires:
  Carp: 0
  Config::Tiny: 0
  DBIx::Simple: 0
  Data::Dumper: 0
  Email::MIME: 0
  English: 0
  IO::Compress::Gzip: 0
  IO::File: 0
  Net::DNS::Resolver: 0
  Net::IP: 0
  Net::SMTPS: 0
  POSIX: 0
  Regexp::Common: 2013031301
  Socket: 2
  Sys::Hostname: 0
  URI: 0
  parent: 0
  strict: 0
  warnings: 0
version: 0.20130514
